# -*- coding: utf-8 -*-
"""Anatel_telefonia.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1N6xM84yFP93A8-szDNeQHaiQ9UJc3o7s
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
from scipy import stats

df = pd.read_csv("/content/br_anatel_telefonia_movel_ddd.csv")

df.dtypes

df.head()

"""# 1. Análise Descritiva"""

print("\nResumo Estatístico:")
print(df["acessos"].describe())

print("\nTotal de Acessos por Tecnologia:")
print(df.groupby("tecnologia")["acessos"].sum())

print("\nTotal de Acessos por Tipo de Sinal:")
print(df.groupby("sinal")["acessos"].sum())

plt.figure(figsize=(10,5))
sns.barplot(data=df, x='tecnologia', y='acessos', hue='sinal')
plt.xticks(rotation=45)
plt.title('Acessos por Tecnologia e Tipo de Sinal')
plt.tight_layout()
plt.show()

"""# 2. Análise Inferencial"""

# Separando os grupos 2G vs 3G
grupo_2g = df[df['sinal'] == '2G']['acessos']
grupo_3g = df[df['sinal'] == '3G']['acessos']

# Teste de normalidade (Shapiro-Wilk)
print("\nTeste de Normalidade:")
print("2G:", stats.shapiro(grupo_2g))
print("3G:", stats.shapiro(grupo_3g))

"""P-valor muito pequeno (< 0.05): Rejeitamos H₀ → os dados não são normalmente distribuídos. Isso quer dizer que os dados de acessos 2G e 3G não seguem uma distribuição normal."""

#podemos usar Mann-Whitney (teste não paramétrico)
teste = stats.mannwhitneyu(grupo_2g, grupo_3g, alternative='two-sided')
print("\nTeste Mann-Whitney U entre acessos 2G e 3G:")
print(teste)

"""Como o p-valor é muito menor que 0.05, rejeitamos H₀.

Há diferença estatisticamente significativa entre o número de acessos 2G e 3G.

Em outras palavras: os acessos entre 2G e 3G não vêm da mesma distribuição – provavelmente, um dos grupos (2G) tem acessos muito maiores que o outro.
"""

sns.boxplot(
    data=df[df['sinal'].isin(['2G', '3G'])],
    x='sinal',
    y='acessos',
    showfliers=False
)
plt.title('Distribuição de Acessos - 2G vs 3G (sem outliers)')
plt.ylabel('Acessos')
plt.xlabel('Tipo de Sinal')
plt.show()

# Separando os grupos 3G vs 4G
grupo3g = df[df['sinal'] == '3G']['acessos']
grupo4g = df[df['sinal'] == '4G']['acessos']

# Teste de normalidade (Shapiro-Wilk)
print("\nTeste de Normalidade:")
print("3G:", stats.shapiro(grupo3g))
print("4G:", stats.shapiro(grupo4g))

"""Ambos os grupos (3G e 4G) não seguem uma distribuição normal, já que seus p-valores são muito menores que 0.05.

Portanto, testes estatísticos paramétricos como o t-teste NÃO devem ser usados.


"""

from scipy.stats import mannwhitneyu
resultado = mannwhitneyu(grupo3g, grupo4g, alternative='two-sided')
print("Mann-Whitney U Result:", resultado)

"""Há diferença estatisticamente significativa entre os acessos das tecnologias 3G e 4G.

Ou seja, os usuários acessam as redes 3G e 4G de forma significativamente diferente (em volume de acessos).
"""

sns.boxplot(
    data=df[df['sinal'].isin(['3G', '4G'])],
    x='sinal',
    y='acessos',
    showfliers=False  # <- isso remove os outliers do gráfico
)
plt.title('Distribuição de Acessos - 3G vs 4G (sem outliers)')
plt.ylabel('Acessos')
plt.xlabel('Tipo de Sinal')
plt.show()